    platform: linux
    image_resource:
        type: docker-image
        source:
          repository: busybox

    run:
        path: sh
        args:
          - -c
          - |
            echo "hello rfdgdgsfdsgdsfgdsf!!!" > greeting
            cat greeting
